---
- name: Copy component files for mutation
  synchronize:
    src: "{{ playbook_dir }}/components/"
    dest: "{{ playbook_dir }}/install"
    recursive: yes
    delete: yes
- name: Find all yaml files
  find:
    paths: "{{ playbook_dir }}/install/"
    patterns: "*.yaml"
    recurse: yes
  register: yamls
- name: Replace namespace in configuration
  replace:
    dest: "{{item.path}}"
    regexp: "enmasse-infra"
    replace: "{{ namespace }}"
  with_items: "{{ yamls.files }}"
- import_role:
    name: crds
- import_role:
    name: none_authservice
  when: '"none" in authentication_services'
- import_role:
    name: standard_authservice
  when: '"standard" in authentication_services'
- import_role:
    name: example_plans
  when: install_example_plans
- import_role:
    name: example_roles
  when: install_example_roles
- import_role:
    name: address_space_controller
- import_role:
    name: enmasse_operator
- import_role:
    name: service_catalog
  when: service_catalog
- import_role:
    name: cluster_service_broker
  when: service_catalog
- import_role:
    name: api_server
  when: api_server
- import_role:
    name: api_service
  when: register_api_server
- import_role:
    name: iot
  when: enable_iot
- import_role:
    name: monitoring-infrastructure
  when: monitoring_infrastructure
- import_role:
    name: service-monitors
  when: service_monitors
- import_role:
    name: grafana-dashboards
  when: service_monitors
- import_role:
    name: alerting
  when: alerting
