apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-application-monitoring-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-application-monitoring-operator
subjects:
- kind: ServiceAccount
  name: prometheus-operator
  namespace: enmasse-monitoring
userNames:
- system:serviceaccount:enmasse-monitoring:prometheus-operator