enmasse:

  iot:

    vertx:
      preferNative: true

    healthCheck:
      insecurePortBindAddress: 0.0.0.0
      insecurePortEnabled: true
      insecurePort: 8088

    tenant:

      app:
        maxInstances: 1
