- hosts: localhost
  vars:
    namespace: enmasseci
    multitenant: true
    enable_rbac: true
    service_catalog: true
    api_server: true
    keycloak_admin_password: admin
    authentication_services:
      - standard
      - none
  roles:
    - enmasse
    - { role: systemtests_dependencies, become: yes }
