apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: enmasse
  name: none-authservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: enmasse
        name: none-authservice
    spec:
      containers:
      - env:
        - name: LISTENPORT
          value: '5671'
        image: docker.io/enmasseproject/none-authservice:latest
        livenessProbe:
          initialDelaySeconds: 60
          tcpSocket:
            port: amqps
        name: none-authservice
        ports:
        - containerPort: 5671
          name: amqps
        resources:
          limits:
            memory: 48Mi
          requests:
            memory: 48Mi
        volumeMounts:
        - mountPath: /opt/none-authservice/cert
          name: none-authservice-cert
          readOnly: false
      volumes:
      - name: none-authservice-cert
        secret:
          secretName: none-authservice-cert
