kind: IoTConfig
apiVersion: iot.enmasse.io/v1alpha1
metadata:
  name: default
spec:
  services:
    deviceConnection:
      jdbc:
        server:
          external:
            username: registry
            password: user12
            url: jdbc:postgresql://postgresql.device-registry-storage.svc/device-registry
    deviceRegistry:
      jdbc:
        server:
          external:
            mode: JSON_TREE
            management:
              connection:
                username: registry
                password: user12
                url: jdbc:postgresql://postgresql.device-registry-storage.svc/device-registry
  adapters:
    mqtt:
      enabled: true
      replicas: 1
      options:
        tenantIdleTimeout: 30m
        maxPayloadSize: 2048
      endpoint:
        secretNameStrategy:
          secretName: iot-mqtt-adapter-tls
    http:
      enabled: true
      replicas: 1
      containers:
        adapter:
          resources:
            limits:
              memory: 128Mi
              cpu: 500m
    lorawan:
      enabled: true
      replicas: 1
    sigfox:
      enabled: true
      replicas: 1
