---
enmasse_serviceaccount: enmasse-admin
enmasse_environment: development
enable_rbac: true
keycloak_admin_user: admin
service_catalog: false
register_api_server: false
standard_authservice_resources: standard_authservice_keycloak
secure_api_server: false
enable_address_space_management: false
api_server: true
install_tenant_clusterroles: true
install_example_plans: true
authentication_services:
  - none
