---
enmasse_serviceaccount: enmasse-admin
enmasse_environment: development
enable_rbac: true
enable_iot: false
keycloak_admin_user: admin
service_catalog: false
standard_authservice_resources: standard_authservice_keycloak
enable_address_space_management: false
install_example_plans: true
install_example_roles: true
authentication_services:
  - none
