apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: enmasse
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enmasse
      name: alertmanager
  template:
    metadata:
      labels:
        app: enmasse
        name: alertmanager
    spec:
      containers:
      - image: ${ALERTMANAGER_IMAGE}
        name: alertmanager
        ports:
        - containerPort: 9093
          name: alertmanager
        volumeMounts:
        - mountPath: /etc/alertmanager
          name: alertmanager-config
          readOnly: true
      volumes:
      - configMap:
          name: alertmanager-config
        name: alertmanager-config
