apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  labels:
    app: enmasse
    alertmanager: main
  name: main
spec:
  image: ${ALERTMANAGER_IMAGE}
  imagePullPolicy: ${IMAGE_PULL_POLICY}
  replicas: 1
  securityContext: {}
  serviceAccountName: alertmanager-main
  containers:
  - image: openshift/oauth-proxy:latest
    imagePullPolicy: Always
    name: oauth-proxy
    ports:
    - containerPort: 8443
      name: proxy
    args:
    - --https-address=:8443
    - --provider=openshift
    - --openshift-service-account=alertmanager-main
    - --upstream=http://localhost:9093
    - --tls-cert=/etc/tls/private/tls.crt
    - --tls-key=/etc/tls/private/tls.key
    - --cookie-secret=SECRET
    volumeMounts:
    - mountPath: /etc/tls/private
      name: secret-alertmanager-proxy-cert
  secrets:
  - alertmanager-proxy-cert
