---
- name: Create project namespace
  shell: oc new-project {{ namespace }} --description="EnMasse Infrastructure"
  register: namespace_exists
  failed_when: namespace_exists.stderr != '' and 'already exists' not in namespace_exists.stderr
  changed_when: namespace_exists.rc == 0
- name: Label namespace
  shell: oc label namespace {{ namespace }} monitoring-key=middleware --overwrite
- name: Select project namespace
  shell: oc project {{ namespace }}
