kind: BuildConfig
apiVersion: v1
metadata:
  name: iot-http-adapter
  labels:
    app: iot-http-adapter
    enmasse-component: iot
spec:
  triggers: 
    - type: ImageChange
    - type: ConfigChange
  source: 
    type: Git
    git:
      uri: https://github.com/eclipse/hono
      ref: "${HONO_VERSION}"
  strategy: 
    type: source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: fabric8-s2i-java-custom:latest
      env:
      - name: MAVEN_ARGS_APPEND
        value: -B -pl org.eclipse.hono:hono-adapter-http-vertx --also-make -Pnetty-tcnative
        #value: -B -pl org.eclipse.hono:hono-adapter-http-vertx --also-make -Pnetty-tcnative -Pmetrics-prometheus
      - name: ARTIFACT_DIR
        value: adapters/http-vertx/target
      - name: ARTIFACT_COPY_ARGS
        value: "*-exec.jar"
  output:
    to:
      kind: ImageStreamTag
      name: iot-http-adapter:latest
