---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: enmasse.io:iot-protocol-adapter
  labels:
    app: enmasse
    component: iot
rules:
  - apiGroups:
    - iot.enmasse.io
    resources:
    - iotprojects
    verbs:
    - create
    - get
    - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: io.enmasse:iot-protocol-adapter-${NAMESPACE}
  labels:
    app: enmasse
    component: iot
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: enmasse.io:iot-protocol-adapter
subjects:
- kind: ServiceAccount
  namespace: ${NAMESPACE}
  name: enmasse.io:iot-protocol-adapter
