apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: enmasse
    name: address-space-controller
  name: address-space-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: enmasse
        name: address-space-controller
    spec:
      containers:
      - env:
        - name: ENABLE_RBAC
          valueFrom:
            configMapKeyRef:
              key: enableRbac
              name: address-space-controller-config
              optional: true
        - name: ENABLE_EVENT_LOGGER
          valueFrom:
            configMapKeyRef:
              key: enableEventLogger
              name: address-space-controller-config
              optional: true
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: environment
              name: address-space-controller-config
              optional: true
        - name: IMPERSONATE_USER
          valueFrom:
            configMapKeyRef:
              key: impersonateUser
              name: address-space-controller-config
              optional: true
        - name: ADDRESS_CONTROLLER_SA
          value: enmasse-admin
        - name: ADDRESS_SPACE_ADMIN_SA
          value: address-space-admin
        - name: TEMPLATE_DIR
          value: /address-space-definitions
        - name: STANDARD_AUTHSERVICE_CONFIG
          value: keycloak-config
        - name: WILDCARD_ENDPOINT_CERT_SECRET
          valueFrom:
            configMapKeyRef:
              key: wildcardEndpointCertSecret
              name: address-space-controller-config
              optional: true
        - name: RESYNC_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: resyncInterval
              name: address-space-controller-config
              optional: true
        - name: RECHECK_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: recheckInterval
              name: address-space-controller-config
              optional: true
        image: docker.io/enmasseproject/address-space-controller:latest
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        name: address-space-controller
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
        volumeMounts:
        - mountPath: /address-space-definitions
          name: address-space-definitions
          readOnly: true
      serviceAccount: enmasse-admin
      volumes:
      - configMap:
          name: address-space-definitions
        name: address-space-definitions
