---
enmasse_tmp_dir: '/tmp/enmasse/'
# vars for clients tasks
systemtests_dir: "{{ playbook_dir }}../../../../../../systemtests"
client_executable_folder: "{{ systemtests_dir }}/client_executable"
cli_java_git_path: "{{ systemtests_dir }}/cli-java"
rhea_path: "{{ client_executable_folder }}/rhea"
maven_root_path: /opt
maven_path: "{{ maven_root_path }}/apache-maven-3.5.2/bin"

# vars for dependencies tasks
nodejs_version: "6"
epel_repo_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
epel_repo_gpg_key_url: "https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
epel_repofile_path: "/etc/yum.repos.d/epel.repo"
