apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: enmasse
    name: address-space-controller
  name: address-space-controller
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: enmasse
      name: address-space-controller
  template:
    metadata:
      labels:
        app: enmasse
        name: address-space-controller
    spec:
      containers:
      - env:
        - name: JAVA_OPTS
          value: -verbose:gc
        - name: ENABLE_EVENT_LOGGER
          valueFrom:
            configMapKeyRef:
              key: enableEventLogger
              name: address-space-controller-config
              optional: true
        - name: EXPOSE_ENDPOINTS_BY_DEFAULT
          valueFrom:
            configMapKeyRef:
              key: exposeEndpointsByDefault
              name: address-space-controller-config
              optional: true
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              key: environment
              name: address-space-controller-config
              optional: true
        - name: TEMPLATE_DIR
          value: /address-space-definitions
        - name: RESOURCES_DIR
          value: /
        - name: STANDARD_AUTHSERVICE_CONFIG_NAME
          value: keycloak-config
        - name: STANDARD_AUTHSERVICE_CREDENTIALS_SECRET_NAME
          value: keycloak-credentials
        - name: STANDARD_AUTHSERVICE_CERT_SECRET_NAME
          value: standard-authservice-cert
        - name: WILDCARD_ENDPOINT_CERT_SECRET
          valueFrom:
            configMapKeyRef:
              key: wildcardEndpointCertSecret
              name: address-space-controller-config
              optional: true
        - name: RESYNC_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: resyncInterval
              name: address-space-controller-config
              optional: true
        - name: RECHECK_INTERVAL
          valueFrom:
            configMapKeyRef:
              key: recheckInterval
              name: address-space-controller-config
              optional: true
        image: ${ADDRESS_SPACE_CONTROLLER_IMAGE}
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        name: address-space-controller
        ports:
        - containerPort: 8080
          name: http
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
            scheme: HTTP
        resources:
          limits:
            memory: 256Mi
          requests:
            memory: 128Mi
        volumeMounts:
        - mountPath: /address-space-definitions
          name: address-space-definitions
          readOnly: true
      serviceAccount: address-space-controller
      volumes:
      - configMap:
          name: address-space-definitions
        name: address-space-definitions
