---
- name: Ensure user has cluster admin access
  shell: oc policy can-i create clusterroles
  register: is_admin
  failed_when: is_admin.stdout == "no"
  when: multitenant
- name: Check if project namespace exists
  shell: oc project {{ namespace }}
  register: namespace_exists
  ignore_errors: True
- name: Create project namespace
  shell: oc new-project {{ namespace }}
  when: namespace_exists.failed
- import_role:
    name: none_authservice
  when: '"none" in authentication_services'
- import_role:
    name: standard_authservice
  when: '"standard" in authentication_services'
- import_role:
    name: address_controller
