kind: BuildConfig
apiVersion: v1
metadata:
  name: iot-operator
  labels:
    app: iot-core
    enmasse-component: iot
spec:
  triggers: 
    - type: ImageChange
    - type: ConfigChange
  source: 
    type: Git
    git:
      uri: https://github.com/enmasseproject/enmasse
      ref: feature/iot
  strategy:
    type: Docker
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: qdrouterd-base:1.4.1
      dockerfilePath: iot/iot-operator/Dockerfile.s2i
  output:
    to:
      kind: ImageStreamTag
      name: iot-operator:latest
