apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: default-with-mqtt
  labels:
    app: enmasse
  annotations:
    enmasse.io/with-mqtt: "true"
spec:
  admin:
    resources:
      memory: 512Mi
  broker:
    maxUnavailable: 1
    resources:
      memory: 512Mi
      storage: 2Gi
    addressFullPolicy: FAIL
    globalMaxSize: 64Mb
  router:
    minReplicas: 2
    resources:
      memory: 512Mi
    linkCapacity: 250
    maxUnavailable: 1
