apiVersion: admin.enmasse.io/v1beta1
kind: BrokeredInfraConfig
metadata:
  name: default
  labels:
    app: enmasse
spec:
  version: 0.26
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 512Mi
      storage: 5Gi
    addressFullPolicy: FAIL
