apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    monitoring-key: middleware
    prometheus: k8s
    role: alert-rules
  name: kube-metrics
  namespace: {{ index .Params "Namespace" }}
spec:
  groups:
  - name: ComponentHealth
    rules:

    - alert: TerminatingPods
      annotations:
        description: Pod {{ "{{" }} $labels.pod {{ "}}" }} has been in a terminating state for over 5 minutes
        severity: warning
      expr: kube_pod_container_status_terminated{exported_namespace="{{ index .Params "Namespace" }}"} == 1
      for: 180s
    - alert: RestartingPods
      annotations:
        description: Pod {{ "{{" }} $labels.pod {{ "}}" }} has restarted over 5 times in the last 10 minutes
        severity: critical
      expr: rate(kube_pod_container_status_restarts_total{exported_namespace="{{ index .Params "Namespace" }}"}[10m]) * 600 > 5
    - alert: RestartingPods
      annotations:
        description: Pod {{ "{{" }} $labels.pod {{ "}}" }} has restarted over 5 times in the last 24 hours
        severity: warning
      expr: rate(kube_pod_container_status_restarts_total{exported_namespace="{{ index .Params "Namespace" }}"}[1d]) * (86400) > 5
    - alert: PendingPods
      annotations:
        description: Pod {{ "{{" }} $labels.pod {{ "}}" }} has been in a pending phase for over 5 minutes.
        severity: warning
      expr: kube_pod_status_phase{phase="Pending",exported_namespace="{{ index .Params "Namespace" }}"} == 1
      for: 180s