kind: BuildConfig
apiVersion: v1
metadata:
  name: iot-tenant-service
  labels:
    app: iot-registry
    enmasse-component: iot
spec:
  triggers: 
    - type: ImageChange
    - type: ConfigChange
  source: 
    type: Git
    git:
      uri: https://github.com/enmasseproject/enmasse
      ref: feature/iot
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: fabric8-s2i-java-custom:latest
      env:
      - name: MAVEN_ARGS_APPEND
        value: -pl io.enmasse:tenant-service --also-make
      - name: ARTIFACT_DIR
        value: iot/tenant-service/target
  output:
    to:
      kind: ImageStreamTag
      name: iot-tenant-service:latest
