---
apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
    name: address-controller-external
  spec:
    ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: amqp
    selector:
      name: address-controller
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
    name: messaging-external
  spec:
    ports:
    - name: amqp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: amqps
      port: 5671
      protocol: TCP
      targetPort: 5671
    selector:
      capability: router
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    labels:
      app: enmasse
    name: mqtt-external
  spec:
    ports:
    - name: mqtt
      port: 1883
      protocol: TCP
      targetPort: 1883
    - name: secure-mqtt
      port: 8883
      protocol: TCP
      targetPort: 8883
    selector:
      name: mqtt-gateway
    type: LoadBalancer
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: enmasse
    name: console-external
  spec:
    ports:
    - name: console-ws
      port: 56720
    - name: console-http
      port: 8080
    selector:
      name: admin
    type: LoadBalancer
kind: List
