kind: ConfigMap
apiVersion: v1
metadata:
  name: infinispan-configuration
data:
  custom-infinispan.xml: |
    <infinispan
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:10.0 http://www.infinispan.org/schemas/infinispan-config-10.0.xsd
                                urn:infinispan:server:10.0 http://www.infinispan.org/schemas/infinispan-server-10.0.xsd"
            xmlns="urn:infinispan:config:10.0"
            xmlns:server="urn:infinispan:server:10.0">

       <cache-container name="clustered" statistics="true">
          <transport cluster="${infinispan.cluster.name}" stack="kubernetes"/>
                    
             <replicated-cache name="LuceneIndexesLocking">
                <indexing index="NONE" />
             </replicated-cache>
                    
             <replicated-cache name="LuceneIndexesMetadata">
                <indexing index="NONE" />
             </replicated-cache>
                    
             <distributed-cache name="LuceneIndexesData">
                <indexing index="NONE" />
             </distributed-cache>

             <distributed-cache owners="3" mode="SYNC" remote-timeout="15000" name="devices">
                <locking isolation="READ_COMMITTED"/>
                <indexing index="PRIMARY_OWNER">
                   <property name="default.indexmanager">
                               org.infinispan.query.indexmanager.InfinispanIndexManager
                   </property>
                </indexing>
             </distributed-cache>
             
             <distributed-cache-configuration name="distributed-volatile-cache-template">
             
                <transaction mode="NONE"/>
                <indexing index="NONE"/>
              </distributed-cache-configuration>

             <distributed-cache owners="3" mode="SYNC" remote-timeout="15000" name="adapterCredentials">
                <transaction mode="NONE"/>
                <indexing index="NONE"/>
             </distributed-cache>

             <distributed-cache owners="3" mode="SYNC" remote-timeout="15000" name="deviceStates">
                <transaction mode="NONE"/>
                <indexing index="NONE"/>
             </distributed-cache>
                   
       </cache-container>

       <server xmlns="urn:infinispan:server:10.0">
          <interfaces>
             <interface name="public">
                <inet-address value="${infinispan.bind.address:127.0.0.1}"/>
             </interface>
          </interfaces>

          <socket-bindings default-interface="public" port-offset="${infinispan.socket.binding.port-offset:0}">
             <socket-binding name="default" port="${infinispan.bind.port:11222}"/>
             <socket-binding name="memcached" port="11221"/>
          </socket-bindings>

          <security>
             <security-realms>
                <security-realm name="default">
                   <properties-realm groups-attribute="Roles">
                      <user-properties path="users.properties" relative-to="infinispan.server.config.path"/>
                      <group-properties path="groups.properties" relative-to="infinispan.server.config.path" />
                   </properties-realm>
                </security-realm>
             </security-realms>
          </security>

          <endpoints socket-binding="default" security-realm="default">
             <hotrod-connector name="hotrod"/>
             <rest-connector name="rest"/>
             <!-- Uncomment to enable the memcached connector -->
             <!-- memcached-connector socket-binding="memcached" / -->
          </endpoints>
       </server>
    </infinispan>

