apiVersion: admin.enmasse.io/v1alpha1
kind: StandardInfraConfig
metadata:
  name: default-with-mqtt
  labels:
    app: enmasse
  annotations:
    enmasse.io/with-mqtt: true
spec:
  version: ${version}
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 512Mi
      storage: 2Gi
    addressFullPolicy: FAIL
  router:
    resources:
      memory: 512Mi
    linkCapacity: 250
