apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-client
  labels:
    app: test-clients
    client: api-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-clients
      client: api-client
  template:
    metadata:
      labels:
        app: test-clients
        client: api-client
    spec:
      containers:
        - name: test-client
          image: docker.io/lulf/external-test-clients:latest
          command: ["/bin/sh"]
          # Edit API url and token when running against external cluster
          args: ["-c", "java -jar /api-client.jar https://kubernetes.svc:8443 token upgrade-test default 10"]
          ports:
            - name: metrics
              containerPort: 8080
