apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: enmasse
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      evaluation_interval: 60s
      scrape_interval: 60s
    scrape_configs:
      - job_name: 'artemis_pod_job'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: artemismetrics.*
            target_label: kubernetes_pod_name
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod_name
      - job_name: 'router_pod_job'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_container_port_name]
            action: keep
            regex: routermetrics.*
            target_label: kubernetes_pod_name
          - action: replace
            source_labels: [__meta_kubernetes_pod_name]
            target_label: kubernetes_pod_name

          - source_labels: [__meta_kubernetes_pod_container_port_name]
